import type { LearningQuestion } from "@/lib/paper1Learning";

export type VerifiedLearningQuestion = LearningQuestion & { topicId: string };

export const verifiedPaper1Questions: VerifiedLearningQuestion[] = [
  {
    topicId: "orientation-paper1-rank1",
    question: "According to the Basic Computer Instructor Paper 1 scheme, how many multiple-choice questions are asked in Paper 1?",
    options: { A: "50", B: "75", C: "100", D: "150" },
    answer: "C",
    explanation: "Paper 1 carries 100 multiple-choice questions. This is a direct exam-scheme fact and must not be confused with total marks or total papers.",
    whyCorrect: "Option C is correct because Paper 1 has 100 MCQs.",
    whyOthersWrong: "50 and 75 are lower than the notified question count; 150 is not the Paper 1 count.",
    subject: "Paper 1 Strategy",
    chapter: "Paper 1 exam map and rank-one method",
    topic: "Exam scheme",
    difficulty: "easy",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Official syllabus document",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "Official Basic Computer Instructor Paper 1 scheme",
    pyqSimilarity: "direct",
    examPatternTag: "direct scheme fact",
    qualityScore: 95,
  },
  {
    topicId: "orientation-paper1-rank1",
    question: "What is the duration of Basic Computer Instructor Paper 1?",
    options: { A: "1 hour", B: "1 hour 30 minutes", C: "2 hours", D: "3 hours" },
    answer: "C",
    explanation: "The notified duration for Paper 1 is 2 hours. Use this for mock pacing: 100 questions in 120 minutes means roughly 72 seconds per question.",
    whyCorrect: "Option C matches the official Paper 1 duration.",
    whyOthersWrong: "The other durations do not match the Paper 1 scheme.",
    subject: "Paper 1 Strategy",
    chapter: "Paper 1 exam map and rank-one method",
    topic: "Exam scheme",
    difficulty: "easy",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Official syllabus document",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "Official Basic Computer Instructor Paper 1 scheme",
    pyqSimilarity: "direct",
    examPatternTag: "direct scheme fact",
    qualityScore: 95,
  },
  {
    topicId: "orientation-paper1-rank1",
    question: "For every wrong answer in Paper 1, what penalty is prescribed?",
    options: { A: "One fourth of the marks", B: "One third of the marks", C: "Half of the marks", D: "No negative marking" },
    answer: "B",
    explanation: "Paper 1 has negative marking. For every wrong answer, one-third of the marks prescribed for that question is deducted. This makes blind guessing risky.",
    whyCorrect: "Option B states the official one-third negative marking rule.",
    whyOthersWrong: "One-fourth, half and no negative marking are not the notified Paper 1 rule.",
    subject: "Paper 1 Strategy",
    chapter: "Paper 1 exam map and rank-one method",
    topic: "Negative marking",
    difficulty: "easy",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Official syllabus document",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "Official Basic Computer Instructor Paper 1 scheme",
    pyqSimilarity: "direct",
    examPatternTag: "direct scheme fact",
    qualityScore: 95,
  },
  {
    topicId: "orientation-paper1-rank1",
    question: "Which group correctly represents the Rajasthan-specific knowledge portion of Paper 1?",
    options: { A: "Pedagogy, DSA, DBMS and OS", B: "Art and Culture, History, Geography, General Science and Current Affairs of Rajasthan", C: "HTML, XML, JavaScript and IoT", D: "C, C++, Java and Python" },
    answer: "B",
    explanation: "Paper 1 includes Rajasthan Art and Culture, History, Geography, General Science and Current Affairs of Rajasthan. The other options belong mainly to Paper 2 technical or pedagogy areas.",
    whyCorrect: "Option B lists the Rajasthan GK and science-current affairs group prescribed for Paper 1.",
    whyOthersWrong: "The other options contain Paper 2 subjects, not the Paper 1 Rajasthan GK block.",
    subject: "Paper 1 Strategy",
    chapter: "Paper 1 exam map and rank-one method",
    topic: "Syllabus mapping",
    difficulty: "easy",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Official syllabus document",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "Official Basic Computer Instructor Paper 1 syllabus",
    pyqSimilarity: "direct",
    examPatternTag: "syllabus identification",
    qualityScore: 95,
  },
  {
    topicId: "art-culture-folk-performance",
    question: "Which dance is widely known as the traditional circular dance of women in Rajasthan?",
    options: { A: "Ghoomar", B: "Kachhi Ghodi", C: "Gavri", D: "Terah Taali" },
    answer: "A",
    explanation: "Ghoomar is associated with women's traditional circular dance in Rajasthan. It is one of the most stable Rajasthan culture facts and can be asked as a direct association or a correct-pair question.",
    whyCorrect: "Ghoomar is the recognised women's circular dance tradition of Rajasthan.",
    whyOthersWrong: "Kachhi Ghodi is linked with dummy-horse performance, Gavri with Bhil folk theatre, and Terah Taali with devotional performance using manjiras.",
    subject: "Rajasthan Art & Culture",
    chapter: "Folk dances, music, instruments and theatre",
    topic: "Folk dances",
    difficulty: "easy",
    importance: "high",
    source: "Learning Library",
    sourceHint: "Verified Rajasthan Art and Culture fact",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "Standard Rajasthan GK culture fact used in state exams",
    pyqSimilarity: "high",
    examPatternTag: "correct association",
    qualityScore: 92,
  },
  {
    topicId: "art-culture-folk-performance",
    question: "Which Rajasthan folk dance is associated with balancing pots or objects while performing?",
    options: { A: "Gair", B: "Bhavai", C: "Maand", D: "Panihari" },
    answer: "B",
    explanation: "Bhavai is associated with balancing pots or objects during performance. Maand and Panihari are singing traditions, not balancing dance forms.",
    whyCorrect: "Bhavai is the dance form known for balancing skill, especially pots or objects.",
    whyOthersWrong: "Gair is a group/festival dance; Maand and Panihari are music/singing traditions, not balancing dances.",
    subject: "Rajasthan Art & Culture",
    chapter: "Folk dances, music, instruments and theatre",
    topic: "Folk dances",
    difficulty: "easy",
    importance: "high",
    source: "Learning Library",
    sourceHint: "Verified Rajasthan Art and Culture fact",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "Standard Rajasthan GK culture fact used in state exams",
    pyqSimilarity: "high",
    examPatternTag: "correct association",
    qualityScore: 92,
  },
  {
    topicId: "art-culture-folk-performance",
    question: "Which folk performance of Rajasthan is especially associated with a dummy-horse theme?",
    options: { A: "Kachhi Ghodi", B: "Chari", C: "Kalbeliya", D: "Kathputli" },
    answer: "A",
    explanation: "Kachhi Ghodi is a Rajasthan folk performance linked with a dummy-horse theme. It is frequently remembered through the horse-costume association.",
    whyCorrect: "Kachhi Ghodi literally and culturally connects with the dummy-horse performance tradition.",
    whyOthersWrong: "Chari is associated with pot/lamp dance, Kalbeliya with the Kalbeliya community dance style, and Kathputli with puppetry.",
    subject: "Rajasthan Art & Culture",
    chapter: "Folk dances, music, instruments and theatre",
    topic: "Folk dances",
    difficulty: "easy",
    importance: "high",
    source: "Learning Library",
    sourceHint: "Verified Rajasthan Art and Culture fact",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "Standard Rajasthan GK culture fact used in state exams",
    pyqSimilarity: "high",
    examPatternTag: "correct association",
    qualityScore: 92,
  },
  {
    topicId: "art-culture-folk-performance",
    question: "Late Hisamuddin is associated with which craft of Rajasthan?",
    options: { A: "Thewa craft", B: "Usta craft", C: "Pat craft", D: "Meenakari" },
    answer: "B",
    explanation: "In the 118A Paper 1 pattern, Late Hisamuddin was asked as an artist associated with Usta craft. This is a typical artist-craft association question.",
    whyCorrect: "The verified answer key for the uploaded 118A paper marks Usta craft for this question.",
    whyOthersWrong: "Thewa, Pat and Meenakari are separate craft traditions and do not match the asked artist-craft pair in this PYQ pattern.",
    subject: "Rajasthan Art & Culture",
    chapter: "Folk arts and handicrafts",
    topic: "Craft-person association",
    difficulty: "medium",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Uploaded 118A Paper 1 with answer key",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "BCI 2022 Basic Paper 1 code 118A, Q9 pattern",
    pyqSimilarity: "direct",
    examPatternTag: "artist-craft association",
    qualityScore: 96,
  },
  {
    topicId: "history-rajput-rulers-battles",
    question: "Which ruler is popularly remembered as the 'forgotten hero of Marwar'?",
    options: { A: "Rao Chandrasen", B: "Rao Gangdev", C: "Maharaja Ajit Singh", D: "Sur Singh" },
    answer: "A",
    explanation: "Rao Chandrasen is remembered for resistance in Marwar and is commonly referred to as the forgotten hero of Marwar in Rajasthan history questions.",
    whyCorrect: "Rao Chandrasen matches the title asked in the uploaded Paper 1 pattern.",
    whyOthersWrong: "The other rulers are important in Marwar history but are not the standard match for this title.",
    subject: "Rajasthan History",
    chapter: "Rajput dynasties, rulers and battles",
    topic: "Ruler-title association",
    difficulty: "medium",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Uploaded 118A Paper 1 with answer key",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "BCI 2022 Basic Paper 1 code 118A, Q11 pattern",
    pyqSimilarity: "direct",
    examPatternTag: "title-person association",
    qualityScore: 96,
  },
  {
    topicId: "history-archaeology-ancient-sites",
    question: "Which archaeological site is associated with the Hanumangarh district and Harappan culture in Rajasthan?",
    options: { A: "Kalibanga", B: "Ahar", C: "Bagor", D: "Bairath" },
    answer: "A",
    explanation: "Kalibanga is the key Harappan site of Rajasthan and is located in Hanumangarh district. It is a high-frequency site-district-culture fact.",
    whyCorrect: "Kalibanga matches Hanumangarh and Harappan culture.",
    whyOthersWrong: "Ahar is linked with Udaipur/Ahar-Banas culture, Bagor with Bhilwara/Mesolithic evidence, and Bairath with Jaipur/Matsya-Ashokan links.",
    subject: "Rajasthan History",
    chapter: "Archaeology and ancient sites",
    topic: "Site-district-culture",
    difficulty: "easy",
    importance: "high",
    source: "Learning Library",
    sourceHint: "Verified Rajasthan History fact",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "Standard Rajasthan history archaeology table",
    pyqSimilarity: "high",
    examPatternTag: "site-district-culture match",
    qualityScore: 94,
  },
  {
    topicId: "geography-minerals-energy-industry",
    question: "Which mine-mineral pair is correctly matched?",
    options: { A: "Degana — Tungsten", B: "Jhamar Kotra — Gypsum", C: "Goth-Manglod — Rock phosphate", D: "Mando-ki-Pal — Marble" },
    answer: "A",
    explanation: "Degana is associated with tungsten. Jhamar Kotra is associated with rock phosphate, Goth-Manglod with gypsum, and Mando-ki-Pal with fluorite/fluorspar.",
    whyCorrect: "Degana — Tungsten is the correct standard mine-mineral pair.",
    whyOthersWrong: "The remaining options deliberately swap important Rajasthan minerals and mines, which is a common exam trap.",
    subject: "Rajasthan Geography",
    chapter: "Minerals, energy and industry",
    topic: "Mine-mineral matching",
    difficulty: "medium",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Uploaded 118A Paper 1 mine-mineral pattern",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "BCI 2022 Basic Paper 1 code 118A, Q45 pattern + standard Rajasthan geography table",
    pyqSimilarity: "high",
    examPatternTag: "mine-mineral match",
    qualityScore: 96,
  },
  {
    topicId: "geography-minerals-energy-industry",
    question: "Which is generally considered Rajasthan's biggest thermal power station among the listed options?",
    options: { A: "Suratgarh Thermal", B: "Kota Thermal", C: "Giral Thermal", D: "Barsingsar Thermal" },
    answer: "A",
    explanation: "The uploaded 118A Paper 1 pattern asks this direct Rajasthan energy fact and the answer key marks Suratgarh Thermal.",
    whyCorrect: "Suratgarh Thermal matches the answer in the uploaded 118A pattern.",
    whyOthersWrong: "Kota, Giral and Barsingsar are power-related locations, but they are not the marked answer for this specific Rajasthan GK question pattern.",
    subject: "Rajasthan Geography",
    chapter: "Minerals, energy and industry",
    topic: "Power stations",
    difficulty: "medium",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Uploaded 118A Paper 1 with answer key",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "BCI 2022 Basic Paper 1 code 118A, Q42 pattern",
    pyqSimilarity: "direct",
    examPatternTag: "energy-location fact",
    qualityScore: 96,
  },
  {
    topicId: "science-biology-human-body",
    question: "Pancreatic juice contains which enzyme that helps in the emulsification/breakdown of fats?",
    options: { A: "Lipase", B: "Pepsin", C: "Trypsin", D: "Amylase" },
    answer: "A",
    explanation: "Lipase is the enzyme associated with fat digestion. Pepsin digests proteins in the stomach, trypsin acts on proteins, and amylase acts on starch/carbohydrates.",
    whyCorrect: "Lipase is the correct enzyme for fat digestion.",
    whyOthersWrong: "Pepsin and trypsin are protein-related enzymes; amylase is carbohydrate/starch-related.",
    subject: "General Science",
    chapter: "Biology: human body systems and functions",
    topic: "Digestive enzymes",
    difficulty: "easy",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Uploaded 118A Paper 1 biology pattern",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "BCI 2022 Basic Paper 1 code 118A, Q33 pattern + standard science fact",
    pyqSimilarity: "direct",
    examPatternTag: "enzyme-function match",
    qualityScore: 96,
  },
  {
    topicId: "science-biology-human-body",
    question: "Which hormone is commonly called the emergency hormone?",
    options: { A: "Thyroxin", B: "Insulin", C: "Adrenaline", D: "Progesterone" },
    answer: "C",
    explanation: "Adrenaline is known as the emergency hormone because it prepares the body for fight-or-flight situations by increasing alertness, heart activity and energy availability.",
    whyCorrect: "Adrenaline is the standard emergency hormone.",
    whyOthersWrong: "Thyroxin regulates metabolism, insulin regulates blood glucose, and progesterone is a reproductive hormone.",
    subject: "General Science",
    chapter: "Biology: hormones and immunity",
    topic: "Hormones",
    difficulty: "easy",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Uploaded 118A Paper 1 biology pattern",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "BCI 2022 Basic Paper 1 code 118A, Q35 pattern + standard science fact",
    pyqSimilarity: "direct",
    examPatternTag: "hormone-function match",
    qualityScore: 96,
  },
  {
    topicId: "science-biology-human-body",
    question: "Which organism causes Kala-azar disease?",
    options: { A: "Amoeba", B: "Plasmodium", C: "Planaria", D: "Leishmania" },
    answer: "D",
    explanation: "Kala-azar, also called visceral leishmaniasis, is caused by Leishmania. Plasmodium causes malaria, not kala-azar.",
    whyCorrect: "Leishmania is the causative organism of kala-azar.",
    whyOthersWrong: "Amoeba, Plasmodium and Planaria are not the cause of kala-azar in the standard disease-agent table.",
    subject: "General Science",
    chapter: "Vitamins, diseases, hormones and immunity",
    topic: "Disease-agent table",
    difficulty: "medium",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Uploaded 118A Paper 1 biology pattern",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "BCI 2022 Basic Paper 1 code 118A, Q39 pattern + standard science fact",
    pyqSimilarity: "direct",
    examPatternTag: "disease-agent match",
    qualityScore: 96,
  },
  {
    topicId: "reasoning-clock-calendar",
    question: "How many times in a day are the hands of a clock straight?",
    options: { A: "22 times", B: "24 times", C: "44 times", D: "48 times" },
    answer: "C",
    explanation: "In 12 hours, clock hands are in a straight line 22 times. In 24 hours, this happens 44 times. This is a standard clock formula fact.",
    whyCorrect: "For one full day, 22 × 2 = 44 times.",
    whyOthersWrong: "22 is the count for 12 hours only; 24 and 48 are common guessing traps.",
    subject: "Logical Reasoning",
    chapter: "Clock and calendar",
    topic: "Clock hands",
    difficulty: "medium",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Uploaded 118A Paper 1 reasoning pattern",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "BCI 2022 Basic Paper 1 code 118A, Q74 pattern + standard clock rule",
    pyqSimilarity: "direct",
    examPatternTag: "clock formula",
    qualityScore: 96,
  },
  {
    topicId: "numeracy-time-work-speed-age",
    question: "In a tournament, 14 teams play league matches. If each team plays against every other team only once, how many matches are played?",
    options: { A: "105", B: "91", C: "85", D: "78" },
    answer: "B",
    explanation: "When every pair of teams plays once, number of matches = n(n-1)/2. For 14 teams: 14 × 13 / 2 = 91.",
    whyCorrect: "The combination formula gives 91 matches.",
    whyOthersWrong: "105, 85 and 78 do not follow the pair-count formula for 14 teams.",
    subject: "Basic Numeracy",
    chapter: "Algebra, equations and mensuration",
    topic: "Counting combinations",
    difficulty: "medium",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Uploaded 118A Paper 1 numeracy pattern",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "BCI 2022 Basic Paper 1 code 118A, Q81 pattern",
    pyqSimilarity: "direct",
    examPatternTag: "combination application",
    qualityScore: 96,
  },
  {
    topicId: "data-interpretation-charts",
    question: "In a pie chart, if a field represents 5% of the total, what is its central angle?",
    options: { A: "1.8°", B: "18°", C: "20°", D: "5°" },
    answer: "B",
    explanation: "Central angle = percentage × 360 / 100. For 5%, angle = 5 × 360 / 100 = 18°.",
    whyCorrect: "Option B is obtained by the standard pie-chart central-angle formula.",
    whyOthersWrong: "1.8° is a decimal-placement error, 20° is an approximation trap, and 5° confuses percentage with angle.",
    subject: "Data Interpretation",
    chapter: "Tables and charts",
    topic: "Pie chart central angle",
    difficulty: "easy",
    importance: "high",
    source: "Previous Year Pattern",
    sourceHint: "Uploaded 118A Paper 1 DI pattern",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "BCI 2022 Basic Paper 1 code 118A, Q83 pattern + DI formula",
    pyqSimilarity: "direct",
    examPatternTag: "pie-chart formula",
    qualityScore: 96,
  },
  {
    topicId: "technology-awareness-paper1",
    question: "Which Digital India platform is commonly associated with accessing multiple government services through a single mobile application?",
    options: { A: "UMANG", B: "BharatNet", C: "DigiLocker", D: "CERT-In" },
    answer: "A",
    explanation: "UMANG is a unified mobile application for accessing many government services. DigiLocker is mainly for digital documents, BharatNet is broadband infrastructure, and CERT-In handles cyber incident response and advisories.",
    whyCorrect: "UMANG matches the one-app-many-government-services idea.",
    whyOthersWrong: "The other options are important government technology terms but serve different purposes.",
    subject: "Rajasthan Current Affairs and Technology Awareness",
    chapter: "Digital India, e-Governance, AI and cybersecurity awareness",
    topic: "Digital India platforms",
    difficulty: "easy",
    importance: "high",
    source: "Learning Library",
    sourceHint: "Official government technology awareness topic",
    reviewStatus: "approved",
    facultyReviewed: true,
    factSource: "Digital India/e-governance awareness",
    pyqSimilarity: "medium",
    examPatternTag: "platform-purpose match",
    qualityScore: 90,
  }
];
