export const dynamic = "force-dynamic";
import Link from "next/link";
import StatCard from "@/components/StatCard";
import { getDashboardData } from "@/lib/serverData";

export default async function HomePage() {
  const data = await getDashboardData();
  return <div className="space-y-6"><section className="card gradient p-8"><p className="text-sm font-medium text-blue-600">Rajasthan Basic Computer Instructor</p><h1 className="mt-2 max-w-4xl text-4xl font-medium leading-tight">Production-ready MCQ exam platform for Paper 1 and Paper 2 practice.</h1><p className="mt-4 max-w-3xl text-muted">Upload JSON tests, start/resume mock exams, auto-save answers, review mistakes, analyze weak topics, export results, and build topic-wise practice sets.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/upload" className="rounded-2xl bg-blue-600 px-5 py-3 font-medium text-white">Upload Test JSON</Link><Link href="/tests" className="rounded-2xl border px-5 py-3 font-medium" style={{borderColor:'var(--border)'}}>View Tests</Link><Link href="/dashboard" className="rounded-2xl border px-5 py-3 font-medium" style={{borderColor:'var(--border)'}}>Dashboard</Link></div></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatCard label="Tests Attempted" value={data?.summary?.totalTestsAttempted || 0} tone="blue"/><StatCard label="Questions Solved" value={data?.summary?.totalQuestionsSolved || 0} tone="green"/><StatCard label="Accuracy" value={`${data?.summary?.accuracy || 0}%`} tone="amber"/><StatCard label="Readiness" value={`${data?.summary?.readinessScore || 0}/100`} helper={data?.summary?.rankPrediction || "Start practicing"}/></section><section className="grid gap-6 lg:grid-cols-3"><div className="card p-5"><h2 className="text-xl font-medium">Test Management</h2><p className="mt-2 text-sm text-muted">Upload, validate, search, filter, replace, delete and manage test metadata.</p></div><div className="card p-5"><h2 className="text-xl font-medium">Exam Mode</h2><p className="mt-2 text-sm text-muted">Timer, full-screen mode, skip, bookmark, auto-save, submit and review answers.</p></div><div className="card p-5"><h2 className="text-xl font-medium">Analytics</h2><p className="mt-2 text-sm text-muted">Paper-wise, topic-wise, difficulty-wise, streak, readiness and weak-topic recommendations.</p></div></section></div>;
}
